project_identifier: tripgo
api_key: 8d45d9d77285a28189afd03c0f9507ee                          
base_path: ./

files:
  -  
    source: '/en/android_localizable_strings.xliff'                                   
    translation: '/%locale%/%original_file_name%'
          
  -  
    source: '/en/iOS.xliff'                                   
    translation: '/%locale%/%original_file_name%'
    languages_mapping:
      locale:
        'es-ES': 'es'
        'pt-PT': 'pt'
        'zh-CN': 'zh-Hans'
        'zh-TW': 'zh-Hant'